ALTER TABLE tenants ADD COLUMN IF NOT EXISTS mp_access_token TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS mp_public_key TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS cbu TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS alias TEXT;
